---
blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/orgs/OpenMANET/discussions
    about: The OpenMANET project relies on volunteers. While we appreciate feature requests, we might lack the manpower to handle them. Ideally, you get familiar with the codebase and attempt to contribute the feature yourself. We recommend to post in the forum, as this is the most likely place to receive feedback on feature requests.
  - name: OpenMANET community
    url: https://github.com/orgs/OpenMANET/discussions
    about: Consider reaching out to our community to get help. OpenMANET is a complex software project with many pitfalls; there is a good chance someone can help you solve your issue in no time.
  - name: OpenMANET documentation
    url: https://openmanet.github.io/docs/
    about: The OpenMANET documentation contains a lot of valuable information.
